CREATE TYPE public.inventory_status AS ENUM 
('Available', 'Pending', 'Sold');

ALTER TABLE inventory
ADD COLUMN inv_status public.inventory_status NOT NULL DEFAULT 'Available';

CREATE TABLE IF NOT EXISTS public.wishlist
(
 wishlist_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 account_id integer NOT NULL,
 inv_id integer NOT NULL,
 date_added TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
 CONSTRAINT fk_account
 	FOREIGN KEY (account_id)
	REFERENCES public.account (account_id)
	ON DELETE CASCADE,
 CONSTRAINT fk_inventory
 	FOREIGN KEY (inv_id)
	REFERENCES public.inventory (inv_id)
	ON DELETE CASCADE,
 CONSTRAINT unique_wishlist_item UNIQUE (account_id, inv_id)
);